scrape:
  domain: http://shipyards.gr
  url: http://shipyards.gr/ship-repair-shipyards?limit=20&limitstart=
  pagination: 20
  min: 0
  max: 300

selector:
  header: .header
  name: div h2 span
  telephone: .mfieldtype_coretelephone div.output
  fax: .mfieldtype_corefax div.output
  website: .mfieldtype_corewebsite div.output
  description: .listing-desc
